import matplotlib.pyplot as plt
import math
import pandas as pd


def PlotVariabili(dato):
    fig = plt.figure()
    plt.subplot(111)
    plt.title('Andamento delle Velocità')
    plt.xlabel('m/s')
    plt.ylabel('R%')
    plt.plot(dato['U'], dato['R%'])
    plt.plot(dato['Cm'], dato['R%'])
    plt.legend(['U', 'Cm'], prop={'size': 8}, loc='upper center')
    plt.show()

    fig1 = plt.figure()
    plt.subplot(111)
    plt.title('Andamento Velocità in Ingresso ed Uscita')
    plt.ylabel('R%')
    plt.xlabel('m/s')
    plt.plot(dato['Cu1'], dato['R%'])
    plt.plot(dato['C1'], dato['R%'])
    plt.plot(dato['W1'], dato['R%'])
    plt.plot(dato['Cu2'], dato['R%'])
    plt.plot(dato['C2'], dato['R%'])
    plt.plot(dato['W2'], dato['R%'])
    plt.legend(['Cu1','C1','W1','Cu2','C2','W2'], prop={'size': 8}, loc='upper center')
    plt.show()

    fig3 = plt.figure()
    plt.subplot(111)
    plt.title('Andamento lavoro di Eulero')
    plt.ylabel('R%')
    plt.xlabel('')
    plt.plot(dato['WE'], dato['R%'])
    plt.legend(['WE'], prop={'size': 8}, loc='upper left')
    plt.show()

    fig4 = plt.figure()
    plt.subplot(111)
    plt.title('Andamento degli angoli Beta')
    plt.ylabel('R%')
    plt.xlabel('°')
    plt.plot(dato['beta1'], dato['R%'])
    plt.plot(dato['beta2'], dato['R%'])
    plt.legend(['beta1', 'beta2'], prop={'size': 8}, loc='upper left')
    plt.show()

    fig5 = plt.figure()
    plt.subplot(111)
    plt.title('Andamento degli angoli Alpha')
    plt.ylabel('R%')
    plt.xlabel('°')
    plt.plot(dato['alpha1'], dato['R%'])
    plt.plot(dato['alpha2'], dato['R%'])
    plt.legend(['alpha1', 'alpha2'], prop={'size': 8}, loc='upper center')
    plt.show()
    return()